apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-infrastructure
  namespace: flux-system
spec:
  interval: 1m0s # detect drift and undo kubectl edits every minute
  wait: true
  timeout: 10m0s
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true
  force: true
  # targetNamespace: prod-flux # set the namespace for all resources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/production

