apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.2.1'
      sourceRef:
        kind: GitRepository
        name: podinfo
      interval: 1m
  values:
    replicaCount: 2
    ingress:
      enabled: true
      hosts: []
      tls:
        enabled: true
        secretName: cert-secret
        certPath: /data/cert
        port: 9899
        # the port used to bind the tls port to the host
        # NOTE: requires privileged container with NET_BIND_SERVICE capability -- this is useful for testing
        # in local clusters such as kind without port forwarding
        hostPort:
    certificate:
      create: true
      # the issuer used to issue the certificate
      issuerRef:
        kind: Issuer
        name: selfsigned
      # the hostname / subject alternative names for the certificate
      dnsNames: []
