apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.2.1'
      sourceRef:
        kind: GitRepository
        name: podinfo
      interval: 1m
  values:
    replicaCount: 2
    tls:
      enabled: true
      secretName: cert-secret
      certPath: /data/cert
      port: 9899
    ingress:
      className: alb
      enabled: true
      hosts: []
      tls: []
    certificate:
      create: true
      issuerRef:
        kind: Issuer
        name: selfsigned
      dnsNames: []
