---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-dns
roleRef:
  namespace: prod-flux
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: prod-flux 

