apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-flux
resources: 
  - ../base/
patches:
- target:
    version: v2beta1
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: ".*"
  patch: |-
    - op: add
      path: /spec/chart/spec/sourceRef/namespace
      value: dev-flux
    - op: add
      path: /spec/values/ingress/hosts
      value: 
      - host: dev-flux.largelyconjecture.com
        paths:
        - path: /
          pathType: ImplementationSpecific
    - op: add
      path: /spec/values/certificate/dnsNames
      value: 
      - dev-flux.largelyconjecture.com
    - op: add
      path: /spec/values/ingress/tls
      value:
      - secretName: podinfo
        hosts: 
        - dev-flux.largelyconjecture.com
