apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment # kpt-set: ${app-name}-deployment
  labels:
    app: dev-kpt # kpt-set: ${environment}-${tech}
  namespace: dev-kpt
spec:
  replicas: 2 # kpt-set: ${nginx-replicas}
  selector:
    matchLabels:
      app: web # kpt-set: ${app-name}
  template:
    metadata:
      labels:
        app: web # kpt-set: ${app-name}
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1 # kpt-set: nginx:${tag}
          ports:
            - protocol: TCP
              containerPort: 80 # kpt-set: ${nginx-port}
