apiVersion: v1
kind: Service
metadata:
  name: web-svc # kpt-set: ${app-name}-svc
  labels:
    app: web # kpt-set: ${app-name}
  namespace: kpt-dev
spec:
  type: LoadBalancer
  selector:
    app: web # kpt-set: ${app-name}
  ports:
    - protocol: TCP
      port: 80
