apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: selfsigned
  name: nginx
  namespace: dev-kpt # kpt-set: ${environment}-kpt
spec:
  rules:
  - host: dev-kpt.largelyconjecture.com # kpt-set: ${environment}-kpt.largelyconjecture.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx
            port:
              number: 80
  tls:
  - hosts:
    - kpt-dev.largelyconjecture.com # kpt-set: kpt-${environment}.largelyconjecture.com
    secretName: cert-secret
