apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-flux
resources: 
  - ../base/
patches:
- target:
    version: v2beta1
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: ".*"
  patch: |-
    - op: add
      path: /spec/chart/spec/sourceRef/namespace
      value: prod-flux
    - op: add
      path: /spec/values/ingress/hosts
      value: 
      - prod-flux.largelyconjecture.com
    - op: add
      path: /spec/values/certificate/dnsNames
      value: 
      - prod-flux.largelyconjecture.com
